version: '3.8'

services:
  downloader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "downloader"

    networks:
      - dwld
    volumes:
      - ../downloader.yaml:/var/downloader.yaml
      - ../downloader.db:/var/downloader.db


networks:
  dwld:
    driver: bridge
