version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "7777:7777"
    networks:
      - dwld
  bot:
    build:
      context: ./dwld-bot
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "bot"
    depends_on:
      - redis
    networks:
      - dwld
    volumes:
      - /bot.yaml:/app/bot.yaml

  downloader:
    build:
      context: ./dwld-downloader
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "downloader"
    depends_on:
      - redis
      - bot
    networks:
      - dwld
    volumes:
      - /downloader.yaml:/app/downloader.yaml

  ftp_sender:
    build:
      context: ./dwld-ftp-sender
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: "ftp_sender"
    depends_on:
      - redis
    networks:
      - dwld
    volumes:
      - /ftp_sender.yaml:/app/ftp_sender.yaml


networks:
  dwld:
    driver: bridge
